name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and Deploy
      run: |
        cp -R * $GITHUB_WORKSPACE/deploy
        ls $GITHUB_WORKSPACE/deploy

